apiVersion: apps/v1
kind: Deployment
metadata:
  name: restgoonch-deployment
  labels:
    app: restgoonch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restgoonch
  template:
    metadata:
      labels:
        app: restgoonch
      annotations:
        prometheus.io/port: '9092'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: restgoonch
        image: thaigoonch/restgoonch:1.2
        ports:
        - name: serviceport
          containerPort: 8080
        resources:
          requests:
            memory: "350Mi"
          limits:
            cpu: "0.70"
            memory: "350Mi"
      nodeSelector:
        goonchrole: "server"
---
kind: Service
apiVersion: v1
metadata:
  name: restgoonch-service
  labels:
    app: restgoonch
spec:
  selector:
    app: restgoonch
  type: ClusterIP
  ports:
  - name: serviceport
    port: 8080
    targetPort: 8080
  - name: prometheusport
    port: 9092
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: restgoonch-servicemonitor
  namespace: default
  labels:
    app: restgoonch
    release: prometheus
spec:
  selector:
    matchLabels:
      app: restgoonch # target service
  endpoints:
  - port: prometheusport